safe: true
lsi: false
pygments: true
paginate: 5
paginate_path: "page:num"

prose:
  rooturl: "_posts"
  siteurl: "http://blog.synk.io/"
  media: "media"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          value: "Insert your title here"
      - name: "allow_comments"
        field:
          element: "select"
          label: "Allow comments?"
          options:
            - name: "Yes"
              value: true
            - name: "No"
              value: false
          selected: true
      - name: "who"
        field:
          element: "select"
          label: "Who is this?"
          placeholder: "Select an author"
          options:
            - name: "Vince Lynch"
              value: "vince"
            - name: "John Martin"
              value: "john"
            - name: "Ben Perreau"
              value: "ben"
          selected: ""
      - name: "bio"
        field:
          element: "text"
          label: "Bio"
          value: "Insert your snippet here"
      - name: "style"
        field:
          element: "select"
          label: "Style"
          options:
            - name: "City (slate grey)"
              value: "1"
            - name: "Blackboard (green)"
              value: "2"
            - name: "Table (dark blue)"
              value: "3"
            - name: "Soundboard (hot red)"
              value: "4"
            - name: "Stairs (light blue)"
              value: "5"
          selected: "1"
